name: Build Carbon
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macOS-15.5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: bazelbuild/setup-bazelisk@v2
      - run: brew install llvm
      - run: bazel build //explorer
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: explorer
          path: bazel-bin/explorer/explorer